[2023-03-15T15:55:54.394+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.map_to_lattice manual__2023-03-15T15:55:51.899015+00:00 [queued]>
[2023-03-15T15:55:54.402+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.map_to_lattice manual__2023-03-15T15:55:51.899015+00:00 [queued]>
[2023-03-15T15:55:54.403+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T15:55:54.403+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-15T15:55:54.404+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T15:55:54.416+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): map_to_lattice> on 2023-03-15 15:55:51.899015+00:00
[2023-03-15T15:55:54.422+0000] {standard_task_runner.py:55} INFO - Started process 22845 to run task
[2023-03-15T15:55:54.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '0_Employee_Sync', 'map_to_lattice', 'manual__2023-03-15T15:55:51.899015+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp1nwnpfiq']
[2023-03-15T15:55:54.428+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask map_to_lattice
[2023-03-15T15:55:54.480+0000] {task_command.py:376} INFO - Running <TaskInstance: 0_Employee_Sync.map_to_lattice manual__2023-03-15T15:55:51.899015+00:00 [running]> on host 9fe6516b8a01
[2023-03-15T15:55:54.539+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=0_Employee_Sync
AIRFLOW_CTX_TASK_ID=map_to_lattice
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T15:55:51.899015+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-15T15:55:51.899015+00:00
[2023-03-15T15:55:54.540+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 48, in map_to_lattice
    return [Employee(employee['UserId']) for employee in employees]
  File "/opt/airflow/dags/test_dag.py", line 48, in <listcomp>
    return [Employee(employee['UserId']) for employee in employees]
TypeError: string indices must be integers
[2023-03-15T15:55:54.553+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=0_Employee_Sync, task_id=map_to_lattice, execution_date=20230315T155551, start_date=20230315T155554, end_date=20230315T155554
[2023-03-15T15:55:54.561+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task map_to_lattice (string indices must be integers; 22845)
[2023-03-15T15:55:54.597+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-15T15:55:54.619+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
