[2023-03-14T18:22:04.794+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DANI_DAG.read_users manual__2023-03-14T18:22:03.279777+00:00 [queued]>
[2023-03-14T18:22:04.801+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: DANI_DAG.read_users manual__2023-03-14T18:22:03.279777+00:00 [queued]>
[2023-03-14T18:22:04.802+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T18:22:04.803+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-14T18:22:04.804+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T18:22:04.815+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): read_users> on 2023-03-14 18:22:03.279777+00:00
[2023-03-14T18:22:04.830+0000] {standard_task_runner.py:55} INFO - Started process 14147 to run task
[2023-03-14T18:22:04.834+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'DANI_DAG', 'read_users', 'manual__2023-03-14T18:22:03.279777+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmptmyt5fjn']
[2023-03-14T18:22:04.837+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask read_users
[2023-03-14T18:22:04.897+0000] {task_command.py:376} INFO - Running <TaskInstance: DANI_DAG.read_users manual__2023-03-14T18:22:03.279777+00:00 [running]> on host 9fe6516b8a01
[2023-03-14T18:22:04.955+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=DANI_DAG
AIRFLOW_CTX_TASK_ID=read_users
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T18:22:03.279777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T18:22:03.279777+00:00
[2023-03-14T18:22:04.964+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 18, in read_users
    print([t for t in employees if t.JobTitle == 'Gaffer'])
  File "/opt/airflow/dags/test_dag.py", line 18, in <listcomp>
    print([t for t in employees if t.JobTitle == 'Gaffer'])
AttributeError: 'str' object has no attribute 'JobTitle'
[2023-03-14T18:22:04.974+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=DANI_DAG, task_id=read_users, execution_date=20230314T182203, start_date=20230314T182204, end_date=20230314T182204
[2023-03-14T18:22:04.983+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task read_users ('str' object has no attribute 'JobTitle'; 14147)
[2023-03-14T18:22:05.007+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-14T18:22:05.024+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
