[2023-03-16T18:33:43.364+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.update_external_users_data manual__2023-03-16T18:33:40.791358+00:00 [queued]>
[2023-03-16T18:33:43.371+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.update_external_users_data manual__2023-03-16T18:33:40.791358+00:00 [queued]>
[2023-03-16T18:33:43.372+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T18:33:43.372+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-16T18:33:43.373+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T18:33:43.380+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): update_external_users_data> on 2023-03-16 18:33:40.791358+00:00
[2023-03-16T18:33:43.387+0000] {standard_task_runner.py:55} INFO - Started process 44713 to run task
[2023-03-16T18:33:43.391+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '0_Employee_Sync', 'update_external_users_data', 'manual__2023-03-16T18:33:40.791358+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp9zomxjtu']
[2023-03-16T18:33:43.394+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask update_external_users_data
[2023-03-16T18:33:43.452+0000] {task_command.py:376} INFO - Running <TaskInstance: 0_Employee_Sync.update_external_users_data manual__2023-03-16T18:33:40.791358+00:00 [running]> on host 9fe6516b8a01
[2023-03-16T18:33:43.503+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=0_Employee_Sync
AIRFLOW_CTX_TASK_ID=update_external_users_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T18:33:40.791358+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T18:33:40.791358+00:00
[2023-03-16T18:33:43.516+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-16T18:33:43.525+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=0_Employee_Sync, task_id=update_external_users_data, execution_date=20230316T183340, start_date=20230316T183343, end_date=20230316T183343
[2023-03-16T18:33:43.562+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-16T18:33:43.581+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
