[2023-03-13T19:26:06.011+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cool_DAG.transform manual__2023-03-13T19:26:04.700367+00:00 [queued]>
[2023-03-13T19:26:06.017+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: cool_DAG.transform manual__2023-03-13T19:26:04.700367+00:00 [queued]>
[2023-03-13T19:26:06.017+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:26:06.018+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-13T19:26:06.018+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:26:06.026+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2023-03-13 19:26:04.700367+00:00
[2023-03-13T19:26:06.031+0000] {standard_task_runner.py:55} INFO - Started process 5071 to run task
[2023-03-13T19:26:06.034+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cool_DAG', 'transform', 'manual__2023-03-13T19:26:04.700367+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpp8nkpx1o']
[2023-03-13T19:26:06.035+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask transform
[2023-03-13T19:26:06.089+0000] {task_command.py:376} INFO - Running <TaskInstance: cool_DAG.transform manual__2023-03-13T19:26:04.700367+00:00 [running]> on host 9fe6516b8a01
[2023-03-13T19:26:06.143+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cool_DAG
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T19:26:04.700367+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-13T19:26:04.700367+00:00
[2023-03-13T19:26:06.144+0000] {logging_mixin.py:120} INFO - segundo
[2023-03-13T19:26:06.144+0000] {python.py:177} INFO - Done. Returned value was: 1.5
[2023-03-13T19:26:06.153+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 189, in execute
    return self._handle_output(return_value=return_value, context=context, xcom_push=self.xcom_push)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in _handle_output
    f'Returned output was type {type(return_value)} expected dictionary for multiple_outputs'
airflow.exceptions.AirflowException: Returned output was type <class 'float'> expected dictionary for multiple_outputs
[2023-03-13T19:26:06.156+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=cool_DAG, task_id=transform, execution_date=20230313T192604, start_date=20230313T192606, end_date=20230313T192606
[2023-03-13T19:26:06.164+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task transform (Returned output was type <class 'float'> expected dictionary for multiple_outputs; 5071)
[2023-03-13T19:26:06.207+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-13T19:26:06.230+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
