[2023-03-15T15:54:24.650+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.fetch_external_user_data manual__2023-03-15T15:54:23.158678+00:00 [queued]>
[2023-03-15T15:54:24.656+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync.fetch_external_user_data manual__2023-03-15T15:54:23.158678+00:00 [queued]>
[2023-03-15T15:54:24.657+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T15:54:24.657+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-15T15:54:24.658+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T15:54:24.665+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): fetch_external_user_data> on 2023-03-15 15:54:23.158678+00:00
[2023-03-15T15:54:24.671+0000] {standard_task_runner.py:55} INFO - Started process 22764 to run task
[2023-03-15T15:54:24.675+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '0_Employee_Sync', 'fetch_external_user_data', 'manual__2023-03-15T15:54:23.158678+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp4i66u8ld']
[2023-03-15T15:54:24.678+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask fetch_external_user_data
[2023-03-15T15:54:24.734+0000] {task_command.py:376} INFO - Running <TaskInstance: 0_Employee_Sync.fetch_external_user_data manual__2023-03-15T15:54:23.158678+00:00 [running]> on host 9fe6516b8a01
[2023-03-15T15:54:24.788+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=0_Employee_Sync
AIRFLOW_CTX_TASK_ID=fetch_external_user_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T15:54:23.158678+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-15T15:54:23.158678+00:00
[2023-03-15T15:54:24.797+0000] {python.py:177} INFO - Done. Returned value was:     Index           UserId  ... DateOfBirth               JobTitle
0       1  88F7B33d2bcf9f5  ...  1945-10-26        Games developer
1       2  f90cD3E76f1A9b9  ...  1910-03-24         Phytotherapist
2       3  DbeAb8CcdfeFC2c  ...  1992-07-02              Homeopath
3       4  A31Bee3c201ef58  ...  2017-08-03      Market researcher
4       5  1bA7A3dc874da3c  ...  1938-12-01     Veterinary surgeon
..    ...              ...  ...         ...                    ...
95     96  5eFda7caAeB260E  ...  1954-07-30      Software engineer
96     97  CCbFce93d3720bE  ...  1932-04-29              Barrister
97     98  2fEc528aFAF0b69  ...  1994-12-28         Police officer
98     99  Adc7ad9B6e4A1Fe  ...  2012-04-12   Broadcast journalist
99    100  b8D0aD3490FC7e1  ...  2016-11-15  IT sales professional

[100 rows x 9 columns]
[2023-03-15T15:54:24.815+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-03-15T15:54:24.816+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-15T15:54:24.826+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=0_Employee_Sync, task_id=fetch_external_user_data, execution_date=20230315T155423, start_date=20230315T155424, end_date=20230315T155424
[2023-03-15T15:54:24.834+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task fetch_external_user_data (Object of type DataFrame is not JSON serializable; 22764)
[2023-03-15T15:54:24.887+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-03-15T15:54:24.910+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
